const assert = require('node:assert/strict')
const P = require('../Preferences.js')
const M = require('../Model.js')
const manifest = require('../manifest.json')
for (const f of P.fields) {
  assert.equal(P.valid(f.key, f.defaultValue), true, f.key)
  assert.equal(P.value({}, f.key), manifest.barWidget.defaults[f.key])
  assert.deepEqual(f, manifest.barWidget.schema.find(s => s.key === f.key))
  assert.equal(P.valid(f.key, null), false)
  assert.ok(P.norwegian[f.label] || f.key === 'leftClick', f.label)
}
for (const locale of ['nb_NO','nn-NO','no','NB_no']) assert.equal(P.language('system',locale),'nb')
for (const locale of ['en_US','de_DE','',undefined]) assert.equal(P.language('system',locale),'en')
assert.equal(P.language('en','nb_NO'),'en')
assert.equal(P.language('nb','en_US'),'nb')
assert.equal(P.language('invalid','nb_NO'),'nb')
assert.equal(P.valid('language','de'),false)
for (const value of [-1,0,21,NaN,Infinity,'5',1.5]) assert.equal(P.valid('volumeStep',value),false)
for (const value of [1,5,20]) assert.equal(P.valid('volumeStep',value),true)
assert.equal(P.valid('showArtist','false'),false)
assert.equal(P.valid('unknown',true),false)
assert.equal(P.value({volumeStep:-5},'volumeStep'),5)
for (const value of ['--help','vivaldi;echo','$(echo bad)','browser\nname',''])
  assert.equal(P.valid('youtubeBrowser',value),false)
assert.equal(P.valid('youtubeProfile','Profile 2'),true)
assert.deepEqual(P.youtubeLaunch({youtubeBrowser:'chromium',youtubeProfile:'Profile 2'}),
  ['uwsm-app','--','chromium','--app=https://youtube.com/','--profile-directory=Profile 2'])
for (const left of ['Open panel','Play/pause']) {
  assert.equal(P.clickAction('left',left),left === 'Open panel' ? 'panel':'playPause')
  assert.equal(P.clickAction('right',left),left === 'Open panel' ? 'playPause':'panel')
  assert.equal(P.clickAction('middle',left),'next')
  assert.equal(P.clickAction('other',left),'none')
}
const player = {dbusName:'org.mpris.MediaPlayer2.chromium.instance1',trackTitle:'Example',metadata:{}}
assert.equal(M.isYoutube(player,'Example - YouTube','chromium'),true)
assert.equal(M.isYoutube(player,'Example - YouTube','vivaldi'),false)
assert.equal(M.isYoutube({...player,dbusName:'org.mpris.MediaPlayer2.chromiumevil'},'Example - YouTube','chromium'),false)
assert.equal(M.isYoutube(player,'Unrelated - YouTube','chromium'),false)
assert.equal(M.isYoutube({...player,metadata:{'xesam:url':'https://youtube.com.evil.test/'}},'Example - YouTube','chromium'),false)
console.log('ok — preferences, click mapping, language, and browser matching tests passed')
